like so

diff --git a/consul-init b/consul-init
--- a/consul-init
+++ b/consul-init
@@ -44,12 +44,28 @@ do_start()
     #   0 if daemon has been started
     #   1 if daemon was already running
     #   2 if daemon could not be started
-    echo "Starting consul-template and backgrounding"
-    exec $DAEMON --pid-file $PIDFILE $DAEMON_ARGS 
-    if { "$?" == 0] ; then
-        echo " OK"
-        return 0
-    fi
+    echo "Starting consul and backgrounding"
+    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --chuid $USER --background --make-pidfile --test > /dev/null \
+        || return 1
+    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --chuid $USER --background --make-pidfile -- \
+        $DAEMON_ARGS \
+        || return 2
+
+    echo -n "Waiting for consul daemon to be listening..."
+    for i in `seq 1 30`; do
+        if ! start-stop-daemon --quiet --stop --test --pidfile $PIDFILE --exec $DAEMON --user $USER; then
+            echo " FAIL: consul process died"
+            return 2
+        fi
+        if "$DAEMON" info >/dev/null; then
+            echo " OK"
+            return 0
+        fi
+        echo -n .
+        sleep 1
+    done
+    echo " FAIL: consul process is alive, but is not listening."
+    return 2
 }
 
 #
@@ -57,15 +73,39 @@ do_start()
 #
 do_stop()
 {
-    kill -2 `cat $PIDFILE`
-    return 0
+    # first try doing this gracefully
+    "$DAEMON" leave
+    # Return
+    #   0 if daemon has been stopped
+    #   1 if daemon was already stopped
+    #   2 if daemon could not be stopped
+    #   other if a failure occurred
+    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+    RETVAL="$?"
+    [ "$RETVAL" = 2 ] && return 2
+    # Wait for children to finish too if this is a daemon that forks
+    # and if the daemon is only ever run from this initscript.
+    # If the above conditions are not satisfied then add some other code
+    # that waits for the process to drop all resources that could be
+    # needed by services started subsequently.  A last resort is to
+    # sleep for some time.
+    start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+    [ "$?" = 2 ] && return 2
+    # Many daemons don't delete their pidfiles when they exit.
+    rm -f $PIDFILE
+    return "$RETVAL"
 }
 
 #
 # Function that sends a SIGHUP to the daemon/service
 #
 do_reload() {
-    kill -HUP `cat $PIDFILE`
+    #
+    # If the daemon can reload its configuration without
+    # restarting (for example, when it is sent a SIGHUP),
+    # then implement that here.
+    #
+    start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
     return 0
 }
 
